name: MapClass
version: 1.4.6
date: 2022-09-17
description: |
    A Package For Mapping Class Orbit Computation

authors:
    - name: Adam James
    - name: Kay Magaard
    - name: Sergey Shpectorov
      url: https://web.mat.bham.ac.uk/S.Shpectorov/index.html
    - name: Helmut Volklein

maintainers:
    - name: Sergey Shpectorov
      url: https://web.mat.bham.ac.uk/S.Shpectorov/index.html

GAP: ">=4.9"

www: https://gap-packages.github.io/MapClass
readme: README.md
packageinfo: https://gap-packages.github.io/MapClass/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/MapClass/releases/download/v1.4.6/MapClass-1.4.6.tar.gz

abstract: |
    The <span class="pkgname">MapClass</span> package calculates the    mapping class group orbits for a given finite group.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    braid orbit, mapping class orbit, Hurwitz loci.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>JMSV22</span>]   <b class='BibAuthor'>James, A., Magaard, K., Shpectorov, S. and Volklein, H.</b>,
     <i class='BibTitle'>MapClass, A Package For Mapping Class Orbit Computation,
             Version 1.4.6</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/MapClass">https://gap-packages.github.io/MapClass</a></span>.
    </p>
    

bibtex: |
    @misc{ MapClass1.4.6,
      author =           {James,  A.  and  Magaard,  K.  and  Shpectorov, S. and
                          Volklein, H.},
      title =            {{MapClass},   A   Package   For  Mapping  Class  Orbit
                          Computation, {V}ersion 1.4.6},
      month =            {Sep},
      year =             {2022},
      note =             {Refereed GAP package},
      howpublished =     {\href        {https://gap-packages.github.io/MapClass}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{MapClass}}},
      keywords =         {braid orbit; mapping class orbit; Hurwitz loci},
      printedkey =       {JMSV22}
    }

